// vue-shared-element/src/components/SharedElement.vue
<template>
  <div v-bind:id="id">
    <slot />
  </div>
</template>

<script>
import html2canvas from "html2canvas";

export default {
  name: "SharedElement",
  props: { id: String, duration: Number },
  data() {
    return {
      test: 123
    };
  },
  methods: {
    transition: function() {
      if (!this.id) return;

      let id_common = this.id + "-common";
      let node = document.getElementById(id_common);
      if (!node) {
        this.visible(true);
        this.generate();
        return;
      }
      node.style.display = "block";
      this.visible(false);

      if (this.props.transitionStart) {
        this.props.transitionStart();
      }

      let current = document.getElementById(this.id);
      html2canvas(current, { scale: 1 }).then(canvas => {
        let rect = current.getBoundingClientRect();
        node.style.top = rect.top + "px";
        node.style.left = rect.left + "px";
        node.style.width = canvas.width + "px";
        node.style.height = canvas.height + "px";
        node.style.background = "url(" + canvas.toDataURL() + ")";
        setTimeout(() => {
          node.remove();
          if (this.props.transitionEnd) {
            this.props.transitionEnd();
          }
          this.visible(true);
          this.generate();
        }, this.duration);
      });
    },
    generate: function() {
      let id_common = this.id + "-common";
      let node = document.getElementById(id_common);
      if (node) {
        node.remove();
      }

      node = document.createElement("DIV");
      node.setAttribute(
        "style",
        "display: none; position: absolute; background-size: 100% 100%; transition: all " +
          this.duration / 1000 +
          "s;"
      );
      node.id = id_common;
      document.body.appendChild(node);

      let current = document.getElementById(this.id);
      html2canvas(current, { scale: 1 }).then(canvas => {
        let rect = current.getBoundingClientRect();
        node.style.top = rect.top + "px";
        node.style.left = rect.left + "px";
        node.style.width = canvas.width + "px";
        node.style.height = canvas.height + "px";
        node.style.background = "url(" + canvas.toDataURL() + ")";
      });
    },
    visible: function(bol) {
      let current = document.getElementById(this.id);
      current.parentNode.style.opacity = bol ? 1 : 0;
    }
  }, // end of methods
  beforeCreate() {
    console.log("beforeCreate");
  },
  created() {
    console.log("created");
  },
  beforeMount() {
    console.log("beforeMount");
  },
  mounted() {
    console.log("mounted");
    this.transition();
  }
};
</script>

<style scoped>
</style>

// react-shared-element/src/SharedElement.js
import React from 'react'
import html2canvas from 'html2canvas'

class SharedElement extends React.Component {

  constructor(props) {
    // console.log('constructor')
    super(props);
    this.state = {
      duration: 300,
    }
  }

  componentDidMount() {
    // console.log('componentDidMount')
    this.transition()
  }

  componentDidUpdate() {
    // console.log('componentDidUpdate')
    this.generate()
  }

  generate = (callback) => {
    const { id } = this.props
    if (!id) return

    let current = document.getElementById(id)
    if (!current) return

    let id_common = id + "-common"
    let node = document.getElementById(id_common)
    if (node) {
      node.remove();
    }

    node = document.createElement("DIV");
    node.setAttribute("style", "display: none; position: absolute; background-size: 100% 100%; transition: all " + (this.state.duration / 1000) + "s;");
    node.id = id_common;
    document.body.appendChild(node);

    html2canvas(current, { scale: 1 }).then(canvas => {
      let rect = current.getBoundingClientRect()
      node.style.top = rect.top + 'px'
      node.style.left = rect.left + 'px'
      node.style.width = canvas.width + 'px'
      node.style.height = canvas.height + 'px'
      node.style.background = 'url(' + canvas.toDataURL() + ')'
      if (callback) callback()
    })
  }

  transition = () => {
    const { id } = this.props
    if (!id) return

    let id_common = id + "-common"
    let node = document.getElementById(id_common)
    if (!node) {
      this.visible(true)
      this.generate()
      return
    }
    node.style.display = 'block'

    let current = document.getElementById(id)

    if (this.props.transitionStart) {
      this.props.transitionStart()
    }

    this.visible(false)
    html2canvas(current, { scale: 1 }).then(canvas => {
      let rect = current.getBoundingClientRect()
      node.style.top = rect.top + 'px'
      node.style.left = rect.left + 'px'
      node.style.width = canvas.width + 'px'
      node.style.height = canvas.height + 'px'
      node.style.background = 'url(' + canvas.toDataURL() + ')'
      setTimeout(() => {
        node.remove();
        if (this.props.transitionStop) {
          this.props.transitionStop()
        }
        this.visible(true)
        this.generate()
      }, this.state.duration);
    })
  }

  visible = (bol) => {
    const { id } = this.props
    if (!id) return
    
    let current = document.getElementById(id)
    current.parentNode.style.opacity = bol ? 1 : 0
  }

  render() {
    // console.log('render')
    const { ...props } = this.props
    return (
      <div {...props}>
        {this.props.children}
      </div>
    )
  }
}

export default SharedElement
